### ISSUE TITLE
Get CodinGamerId doesn't work

### ISSUE THREAD

**Issue by jordiboni** [tdelame/codingame_vscode_extension#4]
I've set my email and password correctly, but running "Get CodinGamerId" fails with this message:

![Captura de pantalla 2021-11-22 a las 18 05 20](https://user-images.githubusercontent.com/13587404/142904272-07d53b1a-eb5f-4283-bc6b-7378f7c37262.png)

**Comment by tdelame** [comment]
Yes, the API changed very recently on the website. There were some messages on the subject in the discord server. It's getting more and more annoying to connect programmatically to the website. The recommended way from the community is first connecting to the website, then fetch the cookie and save it somewhere to use it with your tools. This is the method I use now to fetch my replays, and I will remove such functionalities from the extension.

If you want to write your own tools, have a look at https://github.com/takos22/codingame. The documentation explains how to login https://github.com/takos22/codingame. 

Here is the start of a discussion on the discord server on the subject with another similar solution: https://discord.com/channels/466965651135922206/466965651135922208/902908142982168607

**Comment by tdelame** [comment]
TODO:
- [x] remove get CodinGamer Id from email + password
- [x] remove send bot to CodinGame

**Comment by tdelame** [comment]
I removed the two commands from the latest (2.0.1) version. Closing this issue.
